### ISSUE TITLE
Empty interface is an overloaded type

### ISSUE THREAD

**Issue by rakyll** [go-log/log#1] opened 2017-05-03 18:02 UTC
The current Logger interface has a critical problem that empty interface is already an overloaded type.

```
Log(v ...interface{})
Logf(format string, v ...interface{})
```

In Log, an interface{} argument represent a structured field. Whereas, Logf interface{} arguments are used to format a string. This will lead to a bigger confusion for users who are seeing this API for the first time and will require the interface to document itself very thoughtfully to be useful.

**Comment by asim** [comment] 2017-05-03 18:09
Thanks for the explanation. Do you have some suggestions about what would make more sense? My initial goal was to create the most simplistic version of an interface. Discussion and improvements welcome.

**Comment by natefinch** [comment] 2017-05-03 18:20
I think most people are familiar with fmt.Print and fmt.Printf and therefore will understand how they each work (presumably the methods in this package would work exactly the same as the aforementioned, if not, then yes, that's a problem).

**Comment by rakyll** [comment] 2017-05-03 18:25
@natefinch, I don't think that intention with Log is to provide similar behavior to fmt.Print. How argument value can be serialized is totally left to the implementor's decision. This is critical to be able to support custom structured logging formats.

**Comment by natefinch** [comment] 2017-05-03 18:29
Sounds like @asim needs to write some more docs about what the expected behavior of the methods are, since I think we had different assumptions about what they represent.

**Comment by asim** [comment] 2017-05-03 18:37
Sorry I guess it's not clear, considering there's a single line readme I can see how that might happen. Nate is right. The idea is to provide an extremely simple interface that's completely unopinionated about the underlying implementation thus allowing the user to standardise logging while allowing a standard interface to be passed around with libraries and third parties using a simple logger.Log or logger.Logf with no need for any further understanding or assumptions about logging on their part.

**Comment by natefinch** [comment] 2017-05-03 18:40
From the twitter discussion, it sounded like Asim and Brian expected structured logging to be built on top of this, not underneath. This is kind of key, because you can't have one implementation of this interface that expects key/value pairs in Log (like go-kit) and one implementation that expects a series of unrelated values (like fmt.Print).  The caller needs to know how to use it, so you have to pick one or the other.

**Comment by asim** [comment] 2017-05-03 18:55
Let's take an example which seems to be really common. Libraries log, people say they shouldn't but if we're being honest it happens and it will continue to happen until the end of time. Users of these libraries want to set the logger, maybe so they can send the output to something other than stdout, maybe to define the log level, maybe to add structure to it by predefining tags which identify it as log messages from the library.

In this scenario, the library shouldn't have to care about structured or unstructured logging or anything else. The library wants to log and it simply wants to log some message. It only needs a simple interface. The user can provide an implementation of the interface pre-configured to log to some remote location, with some tags to identify it, etc, etc. 

Might seem like an unorthodox approach but I'm opting for simplicity on one side and pushing the configuration concerns to the side where people seem to have the varying opinions and care a lot about what they use. Let's be honest, if the stdlib *log.Logger was an interface this would all be a non-issue because most of us would just expect that interface to be satisfied.

**Comment by asim** [comment] 2017-05-11 12:42
Appreciate the feedback. Going to close this issue as I feel the interface fits its use case, pushing more of the opinions and complexity to higher level implementations above this. Libraries will simply expect a Logger and call Log/Logf without any need to understand structure or context.

One day we will be free of logs, but until then good luck to all of us.

**Closed by asim** 2017-05-11 12:42 UTC

**Comment by wking** [comment] 2018-11-11 05:48
Based on this discussion, I've filed #9 with both godocs for the interface methods (as suggested [here][1]) and a `WithFields`-style `nest` package to allow subloggers with additional context.

[1]: https://github.com/go-log/log/issues/1#issuecomment-298996161
